#pragma once
#define NUM_SEGMENTS 36
#define NUM_VERTICES_CIRCLE (NUM_SEGMENTS + 2) * 3

#define WIDTH_SCENE 247.75f
#define HEIGHT_SCENE 150.f
#define POINT_NEAR -1.f
#define POINT_FAR 1.f

#define NUM_VERTICES_TABLE 12
#define WIDTH_TABLE WIDTH_SCENE * 0.44f
#define HEIGHT_TABLE HEIGHT_SCENE * 0.76f
#define TABLE_OFFSET_LEFT WIDTH_SCENE * 0.1f
#define TABLE_OFFSET_BOTTOM HEIGHT_SCENE * 0.167f